### ISSUE TITLE
REST API Versioning

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#103]
## Library
* https://github.com/Microsoft/aspnet-api-versioning

## Watching

* https://www.youtube.com/watch?v=dZxt7VKQeLY
* https://www.youtube.com/watch?v=uAYkcHpv-yI

## Implementation Details

We will create compability Layer/API

* Application.Impl 1.0 -> Application.Contract 1.0 + Core 1.0
* Application.Impl 2.0 -> Application.Contract 2.0 + Core 2.0
* Application.Compat 2.0 -> Application.Contract 1.0 + Core 2.0

#### Notes

* Compability layer should be able to used together with new version to serve multiple version from same end point/application/server.
* Initial development will not take care of versioning.
* Initial development will be considered as API v1 (implicit versioning).
* New (say, 2.0) version (package) will be the default version, but should also support v2 call.

#### TODO

- [x] ApiVersion we should be able to add api version information to services/controllers in HttpApi layer by convention (for all services in an assembly).
- [x]  Setting client version info on remote calls -> Should support all of MS's library.
- [x] Should also work for regular api controllers (implements IRemoteService) in modules.
- [x]  Getting client version info from core layer (for backward compability code - not advised).
- [x] ABP API description compability with versioning system
- [x] Host multiple version of a module in the same application. (Compability case)
- [x] Get version from a global point in the c# client.
