### ISSUE TITLE
User management page (CRUD) for Identity module.

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#109]
#### TODO

- [x] Create application services
- [x] Add datatables
- [x] Server side paging & sorting
- [x] Server side searching (single textbox seraches in username and emailaddresses)
- [x] Create new user
- [x] Edit user (update roles)
- [x] Delete user
- [x] Better styling for the table (grid lines etc.)

#### Notes

* Add an "actions" dropdown as first columns for all rows. It will include edit and delete options.
