### ISSUE TITLE
Test the Single-Layer Quick Start Tutorial

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12849]
We should test this with different configurations.

* Document URL: https://docs.abp.io/en/abp/5.3/Tutorials/Todo/Single-Layer/Index
* Use the **5.3.0-rc.3** preview version by specifying the `--preview` parameter to the `abp new` command.

### TODO

- [x] MVC & EF / @braim23  
- [x] MVC & MongoDB / @malikmasis (tested, seems well)
- [x] Angular & EF / @maliming 
- [x] Angular & MongoDB / @demirmusa 
- [x] Blazor Server & EF / @gterdem (tested, working fine)
- [x] Blazor Server & MongoDB / @realLiangshiwei

**Comment by maliming** [comment]
hi @demirmusa 

Please change the `44331` to the MVC port of `angular\src\environments\environment.ts`

This problem has been fixed. https://github.com/volosoft/volo/pull/10456

**Comment by realLiangshiwei** [comment]
![image](https://user-images.githubusercontent.com/16813853/171545207-d00a57fc-e346-4b83-b411-4cf47d6abdbd.png)

### Should we update the image?
![image](https://user-images.githubusercontent.com/16813853/171545268-586cb5fa-1204-4ed2-bb59-c727ee980408.png)
