### ISSUE TITLE
Document Distributed Entity Cache 

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14056]
## Resources

* https://github.com/abpframework/abp/pull/14055
* https://blog.abp.io/abp/ABP.IO-Platform-7.0-RC-Has-Been-Published ("Distributed Entity Cache Service" section)
* https://youtu.be/ElhFMhLNyqY?t=2802

## TODO

- [x] Add a new "Entity Cache" document (`Entity-Cache.md`) under the Caching menu in the documentation.

![image](https://user-images.githubusercontent.com/1210527/204284061-022f103e-0047-421e-903b-114430d3f964.png)

- [x] Write the document based on the resources I've shared above (the document should also mention that ABP automatically invalidates the cache when the entity updated or deleted).
- [x] Add an "Caching Entities" section to the [Caching document](https://docs.abp.io/en/abp/latest/Caching) (after the "Batch Operations" section) and mention about this feature and give reference to that document.
- [x] Add an "Caching Entities" section to the [Entities document](https://docs.abp.io/en/abp/latest/Entities) (before the "Extra Properties" section) and mention about this feature and give reference to that document.
