### ISSUE TITLE
Feat: provide filtering to OAuth error listener

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#18575]
## Description
The purpose is the try to provide custom filter  to [OAuthErrorEvent](https://github.com/abpframework/abp/blob/c742c099b3599fefb6756e83745faf4df3857087/npm/ng-packs/packages/oauth/src/lib/strategies/auth-flow-strategy.ts#L117) listener

## Todo
- [x] Create abstraction to `core` package
- [x] Implement to `oauth` package
- [x] Create documentation for `AuthErrorFilterService`
- [x] #18595
