### ISSUE TITLE
Upgrade angular version to 19.0.x

### ISSUE THREAD

**Issue by sumeyyeKurtulus** [abpframework/abp#21460]
## Angular packages
- [x] migrate ng-schematics

## Update 3rd party packages
- [x] ng-bootstrap
- [x] ng-zorro-antd
- [x] angularx-qrcode (pro)

## Update templates (includes deprecated)
**Normally deprecated templates shouldn't maintain. Yet we're updating @abp packages in templates that's why we'll only maintain angular packages**
- [x] app
- [x] app-no-layers
- [x] module
- [x] ms

### Todo
- [x] Create another issue for refactor components, directives and etc..
- [x] Create a description for this migration and angular APIs refactor to migration guide. We'll notify @EngincanV for next guide
